/**
 * WDK Bundle TypeScript Declarations
 * Generated by @tetherto/wdk-worklet-bundler
 * Generated at: 2026-06-03T19:38:22.554Z
 */

export type NetworkName =
  | 'ethereum'
  | 'polygon'
  | 'arbitrum'
  | 'ton'
  | 'tron'
  | 'solana'
  | 'bitcoin';
export type ProtocolName = never;

export const bundle: string;
